# Generated by Django 4.2.5 on 2023-10-04 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_rename_create_task_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='dateCompleted',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
